name: Hawk
description: 
main: me.cassayre.florian.hawk.Hawk
version: 1.0
api-version: "1.13"

commands:
  hawk:
    description: Hawk's main command. Enter "/hawk help" for help.
    aliases:
      - dl
      - damageslogger
    usage: /hawk
