name: Hawk
description: A tool to track actions and generate web game reports
main: me.cassayre.florian.hawk.Hawk
version: 2.0
api-version: "1.13"

commands:
  hawk:
    description: Hawk's main command. Enter "/hawk help" for help.
    aliases:
      - dl
      - damageslogger
    usage: /hawk
